### Recuperar todas las películas
curl http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/16-16-16-16

### Recuperar toas las películas por género
GET http://localhost:1234/movies?genre=crime

### Crear una película
POST http://localhost:1234/movies
content-type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "Matrix Revolutions",
  "year": 2004,
  "director": "Wachowski Bros.",
  "duration": 112,
  "poster": "https://www.fakeurl.com/matrix_revolutions.jpg",
  "genre": [
    "Action",
    "Sci-fi"
  ],
  "rate": 6.9
}

###
DELETE  http://localhost:1234/movies/7-7-7-7

### Actualizar una película
# Normalmente se utilizaría POST, pero PATCH es más correcto para update
PATCH  http://localhost:1234/movies/16-16-16-16
Content-Type: application/json

{
  "duration": 215,
  "year": 2017
}